---
title: "Text Mining with R - A Tidy Approach"
subtitle: "Applied Examples"
author: "Zach Palmer"
date: "2025-04-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Set Up & Load Data

```{r load-packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytext)
library(igraph)
library(ggraph)
library(gutenbergr)
library(stringr)
```

```{r search-gutenberg}
#gutenberg_metadata %>%
#  filter(str_detect(title, regex("The Skull", ignore_case=TRUE)))
```

```{r load-data}
# all text corpora downloaded from the Gutenberg Project

# The Time Machine, The War of the Worlds, The Invisible Man, and 
# The Door of the Wall, and Other Stories respectively 
hgwells = gutenberg_download(c(35, 36, 5230, 456), meta_fields = "title")

# A Journey to the Centre of the Earth and The Mysterious Island
jv = gutenberg_download(c(18857, 8993), meta_fields = "title")

# Second Variety, The Piper in the Woods, The Variable Man, The Defenders, 
# Mr. Spaceship, and The Skull respectively 
pkd = gutenberg_download(c(32032, 32832, 32154, 28767, 32522, 30255), meta_fields = "title")
```

```{r tidy-data, warning=FALSE, message=FALSE}
tidy_hgw = hgwells %>%
  select(-gutenberg_id) %>%
  mutate(author = "H.G. Wells") %>%
  group_by(title) %>%
  mutate(linenumber = row_number()) %>%
  ungroup() %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

tidy_jv = jv %>%
  select(-gutenberg_id) %>%
  mutate(author = "Jules Verne") %>%
  group_by(title) %>%
  mutate(linenumber = row_number()) %>%
  ungroup() %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

tidy_pkd = pkd %>%
  select(-gutenberg_id) %>%
  mutate(author = "Philip K. Dick") %>%
  group_by(title) %>%
  mutate(linenumber = row_number()) %>%
  ungroup() %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)
```

### Word Frequencies

#### Count Visualizations by Author

```{r}
tidy_books = tidy_hgw %>% 
  bind_rows(tidy_jv, tidy_pkd) %>%
  mutate(word = str_extract(word, "[a-z']+")) %>%
  drop_na()
```

```{r, fig.width=12, fig.height=8}
tidy_books %>%
  count(author, word) %>%
  group_by(author) %>%
  mutate(prop = n / sum(n)) %>%
  select(-n) %>%
  slice_max(prop, n = 10) %>%
  mutate(word = reorder(word, prop)) %>%
  ungroup() %>%
  ggplot(aes(prop, word, fill = author)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~author, ncol = 2, scales = "free") + 
  theme_bw() +
  labs(title = "Most Common Words Across Science Fiction Authors", x = "Frequency", y = NULL)
```

#### Word Frequency Comparisons Between Authors

```{r}
word_frequency = tidy_books %>%
  count(author, word) %>%
  group_by(author) %>%
  mutate(proportion = n / sum(n)) %>% 
  select(-n) %>% 
  pivot_wider(names_from = author, values_from = proportion) %>%
  pivot_longer(c(`Jules Verne`, `Philip K. Dick`), names_to = "author", 
               values_to = "proportion")
```

```{r}
word_frequency %>% head(10)
```

```{r, warning=FALSE, fig.width=12, fig.height=8}
word_frequency %>%
  ggplot(aes(x = proportion, y = `H.G. Wells`, 
             color = abs(`H.G. Wells` - proportion))) +
  geom_abline(color = "gray40", lty = 2) +
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
  geom_text(aes(label = word), check_overlap = TRUE, vjust = 1.5) +
  scale_x_log10(labels = scales::percent_format()) +
  scale_y_log10(labels = scales::percent_format()) +
  scale_color_gradient(limits = c(0, 0.001), 
                       low = "darkslategray4", high = "gray75") +
  facet_wrap(~author, ncol = 2) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "Comparison of Word Usage Between Science Fiction Authors", 
       y = "H.G. Wells", x = NULL)
```



